[project]
name = "concepts-ml"
version = "0.1.0"
description = "Approaches to working with Geospatial foundation models"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
	"claymodel @ git+https://github.com/Clay-foundation/model.git",
	"geopandas",
	"matplotlib",
	"numpy<2",
	"obstore>=0.9.4",
	"pandas<3",
	"pystac-client",
	"PyYAML",
	"python-box",
	"rasterio",
	"scikit-learn",
	"shapely",
	"stackstac",
	"torch",
	"torchvision",
	"umap-learn",
]
